export const FILTER_LIST = 'FILTER_LIST'
export const UPDATE_RESULT_STATE = 'UPDATE_RESULT_STATE'

export const UPDATE_CARDS = 'UPDATE_CARDS'
export const UPDATE_CUR_PAGE_FOR_MOBILE = 'UPDATE_CUR_PAGE_FOR_MOBILE'
export const UPDATE_CUR_PAGE_FOR_WEB = 'UPDATE_CUR_PAGE_FOR_WEB'
export const UPDATE_CUR_PAGE_INDEX = 'UPDATE_CUR_PAGE_INDEX'
export const UPDATE_SCROLL_TOP = 'UPDATE_SCROLL_TOP'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'